version: "3"

networks:
  services-network:
    driver: bridge
      

services:
  api_gateway:
    networks: 
        - services-network
    build:
      context: .
      dockerfile: ./Gateway/Dockerfile
    ports: 
        - 5000:5000 

  products_service:
    networks: 
        - services-network
    build:
      context: .
      dockerfile: ./Services/ProductCatalogService/Dockerfile
    ports:
        - 5001:5001
    depends_on:
        - db
  
  cart_service:
    networks: 
        - services-network 
    build:
      context: .
      dockerfile: ./Services/CartService/Dockerfile
    ports:
        - 5003:5003
    depends_on:
        - db

  checkout_service:
    networks: 
        - services-network 
    build:
      context: .
      dockerfile: ./Services/CheckoutService/Dockerfile
    ports:
        - 5004:5004
    depends_on:
        - db

  inventory_service:
    networks: 
        - services-network
    build:
      context: .
      dockerfile: ./Services/InventoryService/Dockerfile
    ports:
        - 5005:5005
    depends_on:
        - db
  
  relatedproduct_service:
    networks: 
        - services-network
    build:
      context: .
      dockerfile: ./Services/RelatedProductService/Dockerfile
    ports:
        - 5006:5006
    depends_on:
        - db

  review_service:
    networks: 
        - services-network
    build:
      context: .
      dockerfile: ./Services/ReviewService/Dockerfile
    ports:
        - 5007:5007
    depends_on:
        - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    networks: 
        - services-network 
    volumes:
        - ~/var/etc/services-data:/data/db/
    restart: unless-stopped
    ports:
        - 27017:27017
    environment: 
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
       
  
