version: "3"

networks:
  services-network:
    driver: bridge
  products-network:
    driver: bridge

services:
  api_gateway:
    networks: 
        - services-network
    build:
      context: .
      dockerfile: ./Gateway/Dockerfile
    ports: 
        - 5000:5000 
  
  products_api:
    networks: 
        - services-network
        - products-network 
    build:
      context: .
      dockerfile: ./Services/ProductCatalogService/Dockerfile
    ports:
        - 5001:5001
    depends_on:
        - mongodb-products

  mongodb-products:
    image: mongo:latest
    networks: 
        - products-network 
    volumes:
        - ~/var/etc/product-service-data:/data/db
    restart: unless-stopped
    ports:
        - 27017:27017
    environment: 
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
  
 