version: "3"

services:
  products_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
        - 5001:5001
    depends_on:
        - mongodb

  mongodb:
    image: mongo:latest 
    volumes:
        - ~/var/etc/product-service-data:/data/db
    restart: unless-stopped
    ports:
        - 27017:27017
    environment: 
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
  
 